In [1]:
import math
import torch
import torch.nn as nn

In [27]:
torch.ones(3,2)[:,None,:]

tensor([[[1., 1.]],

        [[1., 1.]],

        [[1., 1.]]])

In [28]:
torch.arange(3)[None, :]

tensor([[0, 1, 2]])

In [19]:
horizon = [1,2,3,4]

In [31]:
(torch.arange(4)-(4-1.0)*(0.5))[None, :]

tensor([[-1.5000, -0.5000,  0.5000,  1.5000]])